name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Type Check, Linters & Tests
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET: ci-dummy-auth-secret-min-32-characters-long
      BETTER_AUTH_SECRET: ci-dummy-auth-secret-min-32-characters-long
      BETTER_AUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      GOOGLE_CLIENT_ID: ci-google-client-id
      GOOGLE_CLIENT_SECRET: ci-google-client-secret
      GITHUB_CLIENT_ID: ci-github-client-id
      GITHUB_CLIENT_SECRET: ci-github-client-secret

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: Install dependencies
        run: bun i

      - name: Check types
        run: bun run type-check

      - name: Check linting
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build application
        run: bun run build

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v6
